pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io as Io

/*
 * Palette generated by matugen from the current wallpaper.
 *
 * The file is regenerated by `matugen image <wallpaper>` through the
 * [templates.quickshell] entry in ~/.config/matugen/config.toml, and
 * watched here, so changing the wallpaper re-themes the shell live
 * without a restart.
 *
 * Property names are unchanged from the original static palette, so
 * every existing Colors.* reference keeps working.
 *
 * The FileView is a child rather than the root of this singleton on
 * purpose: FileView exposes a text() method, which would collide
 * with the `text` colour below.
 */
Item {
    id: root

    // ============================================================
    // PALETTE
    //
    // The values below are the original Catppuccin ones. They are
    // the fallback until matugen has written a palette, and remain
    // in effect for any key the template deliberately omits.
    // ============================================================

    property color base: '#1f1f23'
    property color surface: "#313244"

    property color subtext: "#a6adc8"
    property color text: "#ffffff"

    /*
     * `subtext` is tuned as a label colour and measures around 3.8:1
     * against `surface` in a typical matugen palette — under the 4.5:1
     * that small body copy needs. This is the same hue lifted into
     * readable range, for notification bodies and anything else that
     * is a sentence rather than a caption.
     */
    readonly property color bodyText: Qt.lighter(root.subtext, 1.28)

    property color accent: "#89b4fa"
    readonly property color blue: root.accent

    /*
     * Status colours stay fixed on purpose — a "success" that is
     * pink or a "warning" that is teal stops carrying meaning.
     * Only `error` is taken from matugen, which keeps a red-ish
     * hue by construction.
     */
    property color success: "#a6e3a1"
    property color warning: "#f9e2af"
    property color error: "#f38ba8"
    property color urgent: "#ff5f56"

    property color defaultClr: "#3a3a3c"

    readonly property color white: '#ffffff'
    property color gray: '#5a5a5c'

    // ============================================================
    // PANEL TRANSLUCENCY
    // ============================================================

    /*
     * Alpha applied to the bar and popup backgrounds. 1.0 is fully
     * opaque.
     *
     * This is deliberately a separate colour rather than alpha on
     * `base`, because `base` is also used as the foreground on
     * accent-filled buttons, where translucency would be wrong.
     *
     * For a proper frosted look, blur the layer in Hyprland:
     *
     *   hl.layer_rule({ match = "quickshell", blur = true })
     *
     * and drop this to around 0.85.
     */
    property real panelOpacity: 0.94

    readonly property color panel: Qt.rgba(root.base.r, root.base.g, root.base.b, root.panelOpacity)

    // ============================================================
    // GENERATED FILE
    // ============================================================

    readonly property string colorsFile: Quickshell.env("HOME") + "/.config/quickshell/theme/colors.json"

    Io.FileView {
        id: paletteFile

        path: root.colorsFile

        watchChanges: true

        /*
         * Absent before the first matugen run — that is a normal
         * state, not something worth logging on every launch.
         */
        printErrors: false

        onFileChanged: {
            paletteFile.reload();
        }

        onLoaded: {
            root.apply();
        }

        /*
         * FileView does not read on `path` alone unless preloading,
         * so the first read has to be asked for explicitly.
         */
        Component.onCompleted: {
            paletteFile.reload();
        }
    }

    function apply() {
        const raw = paletteFile.text();

        if (!raw || raw.trim() === "")
            return;
        let palette;

        /*
         * matugen rewrites the file in place, so a read can land on
         * a partially written file. Ignore it — the watcher fires
         * again once the write completes.
         */
        try {
            palette = JSON.parse(raw);
        } catch (e) {
            return;
        }

        root.base = palette.base ?? root.base;
        root.surface = palette.surface ?? root.surface;
        root.subtext = palette.subtext ?? root.subtext;
        root.text = palette.text ?? root.text;
        root.accent = palette.accent ?? root.accent;
        root.error = palette.error ?? root.error;
        root.defaultClr = palette.defaultClr ?? root.defaultClr;
        root.gray = palette.gray ?? root.gray;
    }
}
